### ISSUE TITLE
Feature request: adding commons/shared/base project

### ISSUE THREAD

**Issue by vladimiry** [ndx-search/ndx#8]
Such `commons` project could contain for example base tslint/tsconfig/other configs. Maybe also it could incorporate the https://github.com/ndx-search/ndx-utils project. The idea is to have a common configurations base point that the rest of the projects would be based on extending the default configs. That would allow increasing code consistency across the poly-repo projects.

TS supports `tsconfig.json inheritance via Node.js packages` since 3.2 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html

**Comment by localvoid** [comment]
I think that it is a good idea, but I don't want to add any shared runtime dependencies between all packages. What name would you prefer for such package: `ndx-commons`, `ndx-dev-commons`, `ndx-shared`, `ndx-dev-shared` or maybe something else?

**Comment by vladimiry** [comment]
Something with `ndx-dev-` prefix sounds good to me as `dev` indicates that there is no runtime stuff, maybe `ndx-dev-commons`.

**Comment by vladimiry** [comment]
I see `ndx-dev-commons`  has been created, resolved.
